//
// M22HomeAnimationView.h
// Generated by Core Animator version 1.3.2 on 11/21/16.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

@import UIKit;

IB_DESIGNABLE
@interface M22HomeAnimationView : UIView

@property (strong, nonatomic) NSDictionary *viewsByName;

// M22HomeAnimation
- (void)addM22HomeAnimation;
- (void)addM22HomeAnimationWithCompletion:(void (^)(BOOL finished))completionBlock;
- (void)addM22HomeAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)addM22HomeAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)addM22HomeAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)removeM22HomeAnimation;

- (void)removeAllAnimations;

@end