//
// M22IntroAnimationView.h
// Generated by Core Animator version 1.3.2 on 10/6/16.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

@import UIKit;

IB_DESIGNABLE
@interface M22IntroAnimationView : UIView

@property (strong, nonatomic) NSDictionary *viewsByName;

// M22IntroAnimation
- (void)addM22IntroAnimation;
- (void)addM22IntroAnimationWithCompletion:(void (^)(BOOL finished))completionBlock;
- (void)addM22IntroAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)addM22IntroAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)addM22IntroAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)removeM22IntroAnimation;

- (void)removeAllAnimations;

@end