//
// M22PlayerOrbAnimationView.h
// Generated by Core Animator version 1.3.2 on 12/30/16.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

@import UIKit;

IB_DESIGNABLE
@interface M22PlayerOrbAnimationView : UIView

@property (strong, nonatomic) NSDictionary *viewsByName;

// M22PlayerOrbAnimation
- (void)addM22PlayerOrbAnimation;
- (void)addM22PlayerOrbAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)addM22PlayerOrbAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)removeM22PlayerOrbAnimation;

- (void)removeAllAnimations;

@end